# Metadata about this component, to be used in the CMS
spec:
  structures:
    - basic_block
  label: A simple heading component with paragraph text
  description:
  icon: title
  tags: ['text', 'heading']

# Defines the structure of this component, as well as the default values
blueprint:
  heading_level: h1
  heading:
  text:  
  button: bookshop:global/button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading_level: 
    comment: Choose the size of the heading (h1, h2) for this block
    type: select
    options:
      values:
        - h1
        - h2
  text:
    type: markdown